version: '3'
services:
  connortest:
    build: .
    environment:
      - WAIT_TIME=5
      - STOP_TIME=10
      - WATCH_FILE=/test.txt
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/healthy"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
